kemi:
  gemini:
    # Enable/Disable GeminiGenerator auto-configuration
    enabled: true

    # Gemini API Key (Required)
    api-keys:
      - YOUR_API_KEY_1_HERE
      - YOUR_API_KEY_2_HERE

    # Gemini API Base URL
    base-url: https://generativelanguage.googleapis.com

    # List of Gemini models to use (fallback in order)
    models:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite